swagger: '2.0'
info:
  version: 0.0.1
  title: 'tweets'
paths:
  /:
    get:
      description: |
        Gets the resources available via this API.
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/resources1'
  /spec:
    get:
      description: |
        Gets the Swagger spec of this API.
      responses:
        '200':
          description: Success
  /tweets/{tweet_id}:
    get:
      description: |
        Gets a single tweet.
      parameters:
        - name: tweet_id
          in: path
          description: ID of the tweet being requested
          required: true
          type: integer
          format: uint64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/tweet1'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/api_error1'
  /tweets/pages/{pagenum}:
    get:
      description: |
        Gets a page of tweets.
      parameters:
        - name: pagenum
          in: path
          description: Page number (1-indexed)
          required: true
          type: number
          format: uint64
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/tweets1'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/api_error1'
definitions:
  resources1:
    type: object
    properties:
      schema:
        type: string
      resources:
        type: array
        items:
          type: object
          properties:
            url:
              type: string
            methods:
              type: array
              items:
                type: string
  api_error1:
    type: object
    properties:
      schema:
        type: string
      code:
        type: integer
        format: uint32
      message:
        type: string
  tweet1:
    type: object
    properties:
      schema:
        type: string
      tweet_id:
        type: integer
        format: uint64
      user:
        type: string
      name:
        type: string
      body:
        type: string
      timestamp:
        type: string
        format: sqlite3 DATETIME
  tweets1:
    type: object
    properties:
      schema:
        type: string
      tweets:
        type: array
        items:
          $ref: '#/definitions/tweet1'
